#!/bin/bash
set -e

cd $(dirname $0)
source ./common.sh

ver="${1:-latest}" 
build=$(git rev-parse --short HEAD)

base=${base_arr[$base]}
echo build $docker_tag, base: $base  
DOCKER_BUILDKIT=1 docker build . -t $docker_tag --build-arg VER=$ver --build-arg BUILD=$build 
