#!/bin/bash
set -e

cd $(dirname $0)
source ./common.sh

docker run -v /mnt:/mnt -v $(pwd)/id_rsa:/root/.ssh/id_rsa -it --rm --gpus all --workdir /root $docker_tag
# docker run --rm --privileged --gpus 1 nvidia/cuda:11.0.3-base-ubuntu18.04 nvidia-smi
# docker run --rm --privileged --gpus 1 nvidia/cuda:11.7.1-base-ubuntu18.04 nvidia-smi
# docker run --rm --privileged --gpus 1 nvidia/cuda:12.0.0-base-ubuntu18.04 nvidia-smi
